// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockMaster.Data;

#nullable disable

namespace StockMaster.Data.Migrations.Stock
{
    [DbContext(typeof(StockDbContext))]
    [Migration("20260122160841_AddMaterialeAArticolo")]
    partial class AddMaterialeAArticolo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("StockMaster.Models.Stock.Articolo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Materiale")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitaMisura")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codice")
                        .IsUnique()
                        .HasDatabaseName("IX_Articolo_Codice_Unique");

                    b.ToTable("Articoli");
                });

            modelBuilder.Entity("StockMaster.Models.Stock.ArticoloStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArticoloId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodiceArticolo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodiceCommessa")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fase")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FornitoreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LottoRiferimento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantita")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArticoloId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("CodiceCommessa")
                        .HasDatabaseName("IX_ArticoloStock_Commessa");

                    b.HasIndex("Fase")
                        .HasDatabaseName("IX_ArticoloStock_Fase");

                    b.HasIndex("FornitoreId");

                    b.HasIndex("LottoRiferimento")
                        .HasDatabaseName("IX_ArticoloStock_Lotto");

                    b.ToTable("ArticoliStock");
                });

            modelBuilder.Entity("StockMaster.Models.Stock.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Attivo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Indirizzo")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartitaIva")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("StockMaster.Models.Stock.FaseLavorazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Attivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrdineSequenza")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FasiLavorazione");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attivo = true,
                            Codice = "grezzo_stock",
                            Descrizione = "Grezzo in Stock",
                            OrdineSequenza = 1
                        },
                        new
                        {
                            Id = 2,
                            Attivo = true,
                            Codice = "lav_nesting",
                            Descrizione = "Lavorazione Nesting",
                            OrdineSequenza = 2
                        },
                        new
                        {
                            Id = 3,
                            Attivo = true,
                            Codice = "lav_bordatura",
                            Descrizione = "Lavorazione Bordatura",
                            OrdineSequenza = 3
                        },
                        new
                        {
                            Id = 4,
                            Attivo = true,
                            Codice = "verniciatura",
                            Descrizione = "Verniciatura",
                            OrdineSequenza = 4
                        },
                        new
                        {
                            Id = 5,
                            Attivo = true,
                            Codice = "rilavorazione",
                            Descrizione = "Rilavorazione",
                            OrdineSequenza = 5
                        },
                        new
                        {
                            Id = 6,
                            Attivo = true,
                            Codice = "finito_stock",
                            Descrizione = "Finito in Stock",
                            OrdineSequenza = 6
                        },
                        new
                        {
                            Id = 7,
                            Attivo = true,
                            Codice = "consegnato",
                            Descrizione = "Consegnato",
                            OrdineSequenza = 7
                        });
                });

            modelBuilder.Entity("StockMaster.Models.Stock.Fornitore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Attivo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Indirizzo")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartitaIva")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Fornitori");
                });

            modelBuilder.Entity("StockMaster.Models.Stock.TransizioneFase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataTransizione")
                        .HasColumnType("TEXT");

                    b.Property<string>("FaseA")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FaseDa")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LottoRiferimento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatoreId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantita")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DataTransizione")
                        .HasDatabaseName("IX_TransizioneFase_Data");

                    b.HasIndex("LottoRiferimento")
                        .HasDatabaseName("IX_TransizioneFase_Lotto");

                    b.ToTable("TransizioniFase");
                });

            modelBuilder.Entity("StockMaster.Models.Stock.ArticoloStock", b =>
                {
                    b.HasOne("StockMaster.Models.Stock.Articolo", "Articolo")
                        .WithMany("StockRecords")
                        .HasForeignKey("ArticoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockMaster.Models.Stock.Cliente", "Cliente")
                        .WithMany("Ordini")
                        .HasForeignKey("ClienteId");

                    b.HasOne("StockMaster.Models.Stock.Fornitore", "Fornitore")
                        .WithMany("Forniture")
                        .HasForeignKey("FornitoreId");

                    b.Navigation("Articolo");

                    b.Navigation("Cliente");

                    b.Navigation("Fornitore");
                });

            modelBuilder.Entity("StockMaster.Models.Stock.Articolo", b =>
                {
                    b.Navigation("StockRecords");
                });

            modelBuilder.Entity("StockMaster.Models.Stock.Cliente", b =>
                {
                    b.Navigation("Ordini");
                });

            modelBuilder.Entity("StockMaster.Models.Stock.Fornitore", b =>
                {
                    b.Navigation("Forniture");
                });
#pragma warning restore 612, 618
        }
    }
}
